name: Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
      - name: Publish doc to go.dev packages
        run: |
          git pull
          export latest="$(git describe --tags `git rev-list --tags --max-count=1`)"
          curl https://proxy.golang.org/github.com/akhettar/docker-db/@v/$latest.info
